Allow for local dev builds to happen on Mac OS but not requiring any binaries

diff --git a/packages/uaa/pre_packaging b/packages/uaa/pre_packaging
--- a/packages/uaa/pre_packaging
+++ b/packages/uaa/pre_packaging
@@ -9,11 +9,21 @@ cd ${BUILD_DIR}
 tar zxvf maven/apache-maven-3.1.1-bin.tar.gz
 export MAVEN_HOME=${BUILD_DIR}/apache-maven-3.1.1
 
-#unpack Java
-mkdir java
-cd java
-tar zxvf ../uaa/openjdk-1.7.0-u40-unofficial-linux-amd64.tgz
-export JAVA_HOME=${BUILD_DIR}/java
+# Make sure we can see uname
+export PATH=$PATH:/bin:/usr/bin
+
+if [ `uname` = "Darwin" ]; then
+  if [ ! -d $JAVA_HOME ]; then
+    echo "JAVA_HOME properly set is required for Mac OS builds."
+    exit 1
+  fi
+else 
+  #unpack Java
+  mkdir java
+  cd java
+  tar zxvf ../uaa/openjdk-1.7.0-u40-unofficial-linux-amd64.tgz
+  export JAVA_HOME=${BUILD_DIR}/java
+fi
 
 #setup Java and Maven paths
 export PATH=$MAVEN_HOME/bin:$JAVA_HOME/bin:$PATH
