allow MacOS to build without java dependencies

diff --git a/packages/uaa/pre_packaging b/packages/uaa/pre_packaging
--- a/packages/uaa/pre_packaging
+++ b/packages/uaa/pre_packaging
@@ -12,17 +12,22 @@ export MAVEN_HOME=${BUILD_DIR}/apache-maven-3.1.1
 # Make sure we can see uname
 export PATH=$PATH:/bin:/usr/bin
 
+#unpack Java - we support Mac OS 64bit and Linux 64bit otherwise we require JAVA_HOME to point to JDK
 if [ `uname` = "Darwin" ]; then
-  if [ ! -d $JAVA_HOME ]; then
-    echo "JAVA_HOME properly set is required for Mac OS builds."
-    exit 1
-  fi
-else 
-  #unpack Java
+  mkdir java
+  cd java
+  tar zxvf ../uaa/openjdk-1.7.0-u40-unofficial-macosx-x86_64-bundle.tgz
+  export JAVA_HOME=${BUILD_DIR}/java/Contents/Home
+elif [ `uname` = "Linux" ]; then
   mkdir java
   cd java
   tar zxvf ../uaa/openjdk-1.7.0-u40-unofficial-linux-amd64.tgz
   export JAVA_HOME=${BUILD_DIR}/java
+else
+  if [ ! -d $JAVA_HOME ]; then
+    echo "JAVA_HOME properly set is required for non Linux/Darwin builds."
+    exit 1
+  fi	
 fi
 
 #setup Java and Maven paths
